# Site settings
title: 阳光1990
SEOTitle: 阳光1990的博客
header-img: img/post-desk.jpg
email: shanquandeng@163.com
description: "Judge not a book by its cover"
keyword: "阳光1990的博客"
url: "http://sqdeng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/sqdeng/sqdeng.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "态度决定高度,细节决定成败!"
sidebar-avatar: /img/side_header.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
weibo_username:     SunnySpring1991
#zhihu_username:     
github_username:    sqdeng
#facebook_username:  
#jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: 

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID:                            #生成的clientID
  clientSecret:     #生成的clientSecret
  repo: sqdeng.github.io    #仓库名称
  owner: sqdeng    #github用户名
  admin: sqdeng
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 

# Google Analytics
ga_track_id:            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "D",
#        href: "http://"
#    },{
#        title: "简书",
#        href: "http:"
#    }
#]
